routes/web.php
<?php

use App\Models\Order;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.home');
})->name('home');

// Route::get('/cart', function () {
//     return view('frontend.cart');
// })->name('cart');

// Route::get('/checkout', function () {
//     if (empty(session()->get('cart', [])))
//         return redirect(route('cart'));

//     return view('frontend.checkout');
// })->name('checkout');

Route::get('/thank-you/{order}', function ($order_uid) {
    $order = Order::where('uid', $order_uid)->first();

    if (! $order)
        abort(404);

    return view('frontend.thank-you', compact('order'));
})->name('thank-you');

Route::middleware(['auth:sanctum', 'verified'])->get('/account', function () {
    return view('dashboard');
})->name('account');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    $orders = auth()->user()->getOrders()->paginate(10);
    return view('dashboard', compact('orders'));
})->name('dashboard');


// vue
Route::group(['prefix' => '',], function() {
    Route::get('/', function () {
        return view('frontend-vue.home');
    })->name('home');
    
    Route::get('/cart', function () {
        return view('frontend-vue.cart');
    })->name('cart');
    
    Route::get('/checkout', function () {
        // if (empty(session()->get('cart', [])))
        //     return redirect(route('cart'));
    
        return view('frontend-vue.checkout');
    })->name('checkout');
});

app/View/Components/StoreLayout.php
<?php

namespace App\View\Components;

use Illuminate\Support\Facades\View;
use Illuminate\View\Component;

class StoreLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        View::share('cartSession', session()->get('cart', []));

        return view('layouts.store');
    }
}

resources/views/frontend/cart.blade.php
<x-store-layout>
    {{--
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Cart') }}
        </h2>
    </x-slot>
    --}}

    <div class="py-12">
        <!-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg"> -->
                <livewire:cart>
            <!-- </div>
        </div> -->
    </div>
</x-store-layout>

resources/views/frontend/checkout.blade.php
<x-store-layout>
    {{--
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Cart') }}
        </h2>
    </x-slot>
    --}}

    <div class="py-12">
        <!-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg"> -->
                <livewire:checkout>
            <!-- </div>
        </div> -->
    </div>
</x-store-layout>

resources/views/frontend/home.blade.php
<x-store-layout>
    {{--
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Shop') }}
        </h2>
    </x-slot>
    --}}

    <div class="py-12">
        <!-- <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg"> -->
                <livewire:products-list>
            <!-- </div>
        </div> -->
    </div>
</x-store-layout>

resources/views/frontend/thank-you.blade.php
<x-store-layout>
    {{--
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Cart') }}
        </h2>
    </x-slot>
    --}}

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg"> 
                Thank you, your order has been placed.
            </div>
            <div class="flex items-center justify-center min-h-screen bg-gray-100">
            <livewire:receipt :order="$order"></livewire:receipt>
           <!--  <div class="p- mt-5 mb-5">
                <div class="flex items-center justify-center">
                    Thank you very much for doing business with us.
                </div>
                <div class="flex items-end justify-end space-x-3">
                    <button class="px-4 py-2 text-sm text-green-600 bg-green-100">Print</button>
                    <button class="px-4 py-2 text-sm text-blue-600 bg-blue-100">Save</button>
                    <button class="px-4 py-2 text-sm text-red-600 bg-red-100">Cancel</button>
                </div>
            </div> -->
        </div>
        </div>
    </div>
</x-store-layout>